Feature/66 leading swipe action
mikaelacaron/brain-marks pull request #124
Opened 2022-05-02 00:35 UTC by marlonjames71

Progress on issue #66

## What it Does
Adds the ability to move a saved tweet to a different category while maintaining the delete functionality. Also adds the ability to create a new category when attempting to move the tweet to a new category. This is handy when one wants to move a tweet to a category they thought they already created but didn't. Instead of having to quit what you're doing, back out to the main categories screen to create a new category, then go back to where you were to move the tweet, this can all be done without interrupting your flow.

## How I Tested
1. Tap into a category that you know has tweets from the Categories List screen
2. Try swiping left to delete a tweet — the tweet should delete as expected
3. Try swiping right to move a tweet to a different category — Should present the Tweets Categories List (a new categories list screen)
4. Select from one of the categories and tap "Save"
5. The Tweets Category List should dismiss and the tweet should be removed from the tweets list for the currently viewed category
6. Swipe right on another tweet (full swipe should is allowed)
7. Tap "+ New Category" — Should present the `CategorySheetView` to create a new category
8. Name it, and select an icon if you want
9. Tap the "Create" button — The category sheet view will dismiss and the new category should be available as an option on the Tweets Category List screen.
10. Select the new category that was just created and tap "Save"
11. Navigate back to the main Categories List screen — You should see the new category animate onto the list

## Notes
- The `List` for the tweets was made into a plain list style to make the distinction clear as to what screen the user is looking at with a glance.
- The new category list that's used for moving tweets was kept as a grouped inset style list to match the rest of the app. Should feel right at home.
- When a new category is created, the main categories list screen should no longer flash before updating. The problem before was that every time `getCategories()` was called, the categories array was being set to an empty array first which was causing the empty state view to flash for a split second before the new data was populated. Now it just overwrites the categories array with the new data. It no longer sets it to an empty array anymore.
- There are other minor code cleanups with this PR as well — only for files that I was working in

## Screenshot
Here's a [link](https://cln.sh/Z9NOge) to the video that shows the new feature.

2022-05-29 22:01 UTC, marlonjames71 commented on brain-marks/Categories/CategoryListViewModel.swift
> -        categories = []
Was causing the screen to flash

2022-10-01 21:09 UTC, mikaelacaron approved these changes
Great work!! @marlonjames71
Sorry the PR took so long, I'm finally getting back around to cleaning up the repo for Hacktoberfest 22!

2022-10-01 21:41 UTC, mikaelacaron requested changes
@marlonjames71 
After merging `dev` into this branch, some functionality breaks.
* Reloading the category list when a new category is created doesn't happen,
* the edit functionality for rearranging the list also breaks
* But your new code for moving a tweet looks like it still works

I love everything you've done, if you could work on this for Hacktoberfest 2022 that'd be great!

2022-10-01 21:54 UTC, mikaelacaron commented
I'm going to close this PR because of change I'm about to make, but if you want to contribute again for Hacktoberfest, you're more than welcome to! Thanks again! ❤️

2022-10-01 21:54 UTC, closed without merging